<script lang="ts">
	/**
	 * THE STOCK SCREEN.
	 *
	 * One component with a responsive branch rather than two routes, because it is one screen and
	 * one URL: a filter somebody bookmarked on their laptop has to open on their phone. The two
	 * compositions genuinely differ — a five-column table you scan, against a stack of cards you
	 * read one at a time — which is why this is a branch and not a stylesheet.
	 *
	 * THE HEADER SENTENCE — "48 items counted, 3 running low." — is generated by `summarySentence`,
	 * which is pure and tested. The design's reassurance for this module is one sentence and the
	 * concern it becomes is the same sentence with the other answer; the only way to keep that
	 * true across every shape the data can take is to make the shapes a test.
	 *
	 * THE TWO EMPTY STATES ARE STRUCTURALLY DIFFERENT, which is SPA-6's acceptance criterion. An
	 * empty MODULE is a panel with a way out of itself; an empty FILTER is one sentence and no
	 * call to action. Offering "Add an item" under an empty "Running low" tab would be the
	 * interface misreading good news as a lack. The branch is on `counts`, not on `items.length`,
	 * because that is the difference between "you have nothing" and "nothing matched".
	 */
	import Package from '@lucide/svelte/icons/package';
	import Plus from '@lucide/svelte/icons/plus';
	import { Button } from '$lib/ui';
	import { PrimaryAction } from '$lib/components/shell';
	import {
		emptyCopy,
		summarySentence,
		type InventoryFilter,
		type InventoryListItem,
		type InventorySort,
		type SortDirection
	} from '$lib/core/inventory';
	import type { Money } from '$lib/core/money';
	import FilterTabs from './FilterTabs.svelte';
	import ItemCard from './ItemCard.svelte';
	import ItemTable from './ItemTable.svelte';
	import SummaryBar from './SummaryBar.svelte';

	let {
		items,
		counts,
		filter,
		itemCount,
		lowCount,
		locationCount,
		valueAtCost,
		uncosted,
		page,
		pageCount,
		sort,
		direction,
		hrefFor,
		pageHref,
		sortHref,
		readOnly = false,
		oncreate
	}: {
		items: readonly InventoryListItem[];
		counts: Readonly<Record<InventoryFilter, number>>;
		filter: InventoryFilter;
		itemCount: number;
		lowCount: number;
		locationCount: number;
		valueAtCost: Money;
		uncosted: number;
		page: number;
		pageCount: number;
		sort: InventorySort;
		direction: SortDirection;
		hrefFor: (filter: InventoryFilter) => string;
		pageHref: (page: number) => string;
		sortHref: (sort: InventorySort) => string;
		/** A removed module stays readable — nothing here may write. */
		readOnly?: boolean;
		oncreate?: () => void;
	} = $props();

	const sentence = $derived(summarySentence({ itemCount, lowCount, locationCount }));

	/** Nothing at all, in any state — not merely nothing under this tab. */
	const moduleIsEmpty = $derived(counts.all === 0 && counts.archived === 0);
</script>

<!-- Page and filter links carry a query string, not a route id — see the note in `ItemTable`. -->
<!-- eslint-disable svelte/no-navigation-without-resolve -->

<div class="mx-auto w-full max-w-6xl px-4 py-8 lg:px-8">
	<div class="flex flex-wrap items-start justify-between gap-3">
		<div class="min-w-0">
			<!-- The module eyebrow: the icon and the word, both in the inventory accent. -->
			<p class="flex items-center gap-1.5 text-helper font-medium text-inventory-ink">
				<Package class="size-3.5 text-inventory" aria-hidden="true" />
				Inventory
			</p>
			<h1 class="mt-1 text-[20px] font-semibold text-ink lg:text-[24px]">Stock</h1>
			<!-- The screen's whole state, in one sentence a person would say out loud. -->
			<p class="mt-1 text-ui text-ink-secondary">{sentence}</p>
		</div>

		{#if !readOnly}
			<Button onclick={oncreate} class="hidden lg:inline-flex">
				<Plus class="size-4" aria-hidden="true" />
				New item
			</Button>
		{/if}
	</div>

	<!-- The summary bar is a desktop composition. On a phone the tabs carry the same counts. -->
	<div class="hidden lg:block">
		<SummaryBar {itemCount} {lowCount} {locationCount} {valueAtCost} {uncosted} />
	</div>

	<div class="overflow-x-auto lg:overflow-visible">
		<FilterTabs active={filter} {counts} {hrefFor} />
	</div>

	{#if moduleIsEmpty}
		<!--
			THE EMPTY MODULE. A panel, not a sentence — because the way out of it is a button, and
			this is the one state where the interface has something to offer rather than something to
			report.
		-->
		<div
			class="mt-8 flex flex-col items-start gap-2.5 rounded-[10px] border border-line-default
				bg-surface-card p-7"
		>
			<Package size={22} strokeWidth={1.75} class="text-inventory" aria-hidden="true" />
			<h2 class="text-[16px] leading-snug text-ink">Nothing in your stock yet</h2>
			<p class="max-w-[380px] text-[13px] leading-relaxed text-ink-secondary">
				{emptyCopy('all')}
			</p>
			{#if !readOnly}
				<Button class="mt-1.5" onclick={oncreate}>
					<Plus class="size-4" aria-hidden="true" />
					Add an item
				</Button>
			{/if}
		</div>
	{:else if items.length === 0}
		<!-- A FILTER THAT MATCHED NOTHING. One line, no panel, no button. -->
		<p class="mt-8 text-ui text-ink-secondary">{emptyCopy(filter, counts.archived > 0)}</p>
	{:else}
		<div class="hidden lg:block">
			<ItemTable {items} {sort} {direction} {sortHref} />
		</div>

		<div class="mt-4 flex flex-col gap-3 lg:hidden">
			{#each items as row (row.item.id)}
				<ItemCard {row} />
			{/each}
		</div>
	{/if}

	{#if pageCount > 1}
		<!--
			Paging, because a joinery has fifty parts and a hardware shop has five thousand. Links
			rather than buttons, so a page can be bookmarked and the back button works.
		-->
		<nav class="mt-6 flex items-center justify-between gap-4" aria-label="Pages of stock">
			<a
				href={pageHref(page - 1)}
				aria-disabled={page <= 1}
				class="rounded-[7px] border border-line-control px-3 py-1.5 text-ui text-ink-secondary
					outline-none hover:bg-surface-raised/60 focus-visible:outline-2
					focus-visible:outline-offset-2 focus-visible:outline-brand-focus-ring
					aria-disabled:pointer-events-none aria-disabled:opacity-40"
			>
				Previous
			</a>
			<p class="text-helper text-ink-muted">Page {page} of {pageCount}</p>
			<a
				href={pageHref(page + 1)}
				aria-disabled={page >= pageCount}
				class="rounded-[7px] border border-line-control px-3 py-1.5 text-ui text-ink-secondary
					outline-none hover:bg-surface-raised/60 focus-visible:outline-2
					focus-visible:outline-offset-2 focus-visible:outline-brand-focus-ring
					aria-disabled:pointer-events-none aria-disabled:opacity-40"
			>
				Next
			</a>
		</nav>
	{/if}

	{#if !readOnly && !moduleIsEmpty}
		<!--
			The phone's primary action. `PrimaryAction` is `sticky`, not `fixed` — so at the bottom
			of the scroll it comes to rest AFTER the last card rather than on top of it.
			Deliberately absent from the empty-module state, which already has its own button.
		-->
		<PrimaryAction class="lg:hidden" onclick={oncreate}>New item</PrimaryAction>
	{/if}
</div>
