<script lang="ts">
	/**
	 * THE INVOICES SCREEN — T20 on a desktop, T22 on a phone.
	 *
	 * One component with a responsive branch rather than two routes, because it is one screen and
	 * one URL: a filter somebody bookmarked on their laptop has to open on their phone.
	 *
	 * The two compositions are genuinely different, which is why this is a branch and not a
	 * stylesheet. The desktop is a six-column table you scan; the phone is a stack of cards you
	 * read one at a time, with the amount as the largest thing on each — because the question on
	 * a phone is *did they pay*, and the question on a laptop is *what is the state of things*.
	 *
	 * THE HEADER SENTENCE — "6 unpaid, none overdue. One is due on Monday." — is generated by
	 * `summarySentence`, which is pure and tested. T20 asks for a line that "must read like a
	 * person wrote it", and the only way to keep that true across every shape the data can take
	 * is to make the shapes a test.
	 */
	import Receipt from '@lucide/svelte/icons/receipt';
	import Plus from '@lucide/svelte/icons/plus';
	import { Button } from '$lib/ui';
	import { PrimaryAction } from '$lib/components/shell';
	import {
		summarySentence,
		type InvoiceFilter,
		type InvoiceListItem,
		type InvoiceSort,
		type SortDirection,
		type SummaryFacts
	} from '$lib/core/invoicing';
	import type { CalendarDate } from '$lib/core/calendar';
	import type { Money } from '$lib/core/money';
	import FilterTabs from './FilterTabs.svelte';
	import InvoiceCard from './InvoiceCard.svelte';
	import InvoiceTable from './InvoiceTable.svelte';
	import SummaryBar from './SummaryBar.svelte';

	let {
		invoices,
		counts,
		filter,
		today,
		summary,
		owed,
		dueThisWeek,
		overdue,
		page,
		pageCount,
		sort,
		direction,
		hrefFor,
		pageHref,
		sortHref,
		exportHref,
		readOnly = false,
		creating = false,
		oncreate,
		onremind,
		onmarkpaid
	}: {
		invoices: readonly InvoiceListItem[];
		counts: Readonly<Record<InvoiceFilter, number>>;
		filter: InvoiceFilter;
		today: CalendarDate;
		summary: SummaryFacts;
		owed: Money;
		dueThisWeek: Money;
		overdue: Money;
		page: number;
		pageCount: number;
		sort: InvoiceSort;
		direction: SortDirection;
		hrefFor: (filter: InvoiceFilter) => string;
		pageHref: (page: number) => string;
		sortHref: (sort: InvoiceSort) => string;
		exportHref: string;
		/** A removed module stays readable and exportable — but nothing here may write. */
		readOnly?: boolean;
		creating?: boolean;
		oncreate?: () => void;
		onremind?: (id: string) => void;
		onmarkpaid?: (id: string) => void;
	} = $props();

	/**
	 * The ONE card that gets buttons on a phone.
	 *
	 * The most urgent unpaid invoice on the page: overdue first, then the soonest due. Everything
	 * else is information. Computed here rather than per card so that "exactly one" is a property
	 * of the list and not a coincidence of the data.
	 */
	const actionableId = $derived.by(() => {
		const candidates = invoices.filter(
			(i) => i.status === 'overdue' || i.status === 'sent' || i.status === 'viewed'
		);
		if (candidates.length === 0) return null;

		const overdueFirst = candidates.filter((i) => i.status === 'overdue');
		const pool = overdueFirst.length > 0 ? overdueFirst : candidates;

		return pool.reduce((soonest, i) =>
			(i.dueDate ?? '9999-12-31') < (soonest.dueDate ?? '9999-12-31') ? i : soonest
		).id;
	});

	const sentence = $derived(summarySentence(summary, today));
</script>

<!-- Page links carry a query string, not a route id — see the note in `InvoiceTable.svelte`. -->
<!-- eslint-disable svelte/no-navigation-without-resolve -->

<div class="mx-auto w-full max-w-6xl px-4 py-8 lg:px-8">
	<div class="flex flex-wrap items-start justify-between gap-3">
		<div class="min-w-0">
			<!-- The module eyebrow: the icon and the word, both in the invoicing accent. -->
			<p class="flex items-center gap-1.5 text-helper font-medium text-invoicing-ink">
				<Receipt class="size-3.5 text-invoicing" aria-hidden="true" />
				Invoicing
			</p>
			<h1 class="mt-1 text-[24px] font-semibold text-ink lg:text-[24px]">
				<span class="hidden lg:inline">Invoices</span>
				<span class="text-[20px] lg:hidden">Invoices</span>
			</h1>
			<!-- The screen's whole state, in one sentence a person would say out loud. -->
			<p class="mt-1 text-ui text-ink-secondary">{sentence}</p>
		</div>

		{#if !readOnly}
			<Button onclick={oncreate} disabled={creating} class="hidden lg:inline-flex">
				<Plus class="size-4" aria-hidden="true" />
				{creating ? 'Starting…' : 'New invoice'}
			</Button>
		{/if}

		<!-- The phone's header action is a text link; the primary lives in the sticky button. -->
		<a
			href={exportHref}
			data-sveltekit-reload
			class="text-[13px] text-ink-secondary underline-offset-2 outline-none hover:underline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-focus-ring focus-visible:outline-solid lg:hidden"
		>
			Export
		</a>
	</div>

	<!-- The summary bar is a desktop composition. On a phone the pills carry the same counts. -->
	<div class="hidden lg:block">
		<SummaryBar {owed} {dueThisWeek} {overdue} overdueCount={summary.overdueCount} {exportHref} />
	</div>

	<div class="overflow-x-auto lg:overflow-visible">
		<FilterTabs active={filter} {counts} {hrefFor} />
	</div>

	{#if invoices.length === 0}
		<p class="mt-8 text-ui text-ink-secondary">
			{#if filter === 'all'}
				Nothing invoiced yet. Start one and it will save as you go — you can close it and come back.
			{:else}
				Nothing here. That is usually good news.
			{/if}
		</p>
	{:else}
		<!-- Desktop: the six-column table. -->
		<div class="hidden lg:block">
			<InvoiceTable {invoices} {today} {sort} {direction} {sortHref} />
		</div>

		<!-- Phone: cards. The sticky primary below occupies flow, so nothing needs clearance. -->
		<div class="mt-4 flex flex-col gap-3 lg:hidden">
			{#each invoices as invoice (invoice.id)}
				<InvoiceCard
					{invoice}
					{today}
					needsAction={!readOnly && invoice.id === actionableId}
					onremind={() => onremind?.(invoice.id)}
					onmarkpaid={() => onmarkpaid?.(invoice.id)}
				/>
			{/each}
		</div>
	{/if}

	{#if pageCount > 1}
		<!--
			Paging, because 24 invoices fit and a real business will have thousands. Links rather
			than buttons, so a page can be bookmarked and the back button works.
		-->
		<nav class="mt-6 flex items-center justify-between gap-4" aria-label="Pages of invoices">
			<a
				href={pageHref(page - 1)}
				aria-disabled={page <= 1}
				class="rounded-[7px] border border-line-control px-3 py-1.5 text-ui text-ink-secondary
					outline-none hover:bg-surface-raised/60 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-focus-ring
					focus-visible:outline-solid aria-disabled:pointer-events-none aria-disabled:opacity-40"
			>
				Previous
			</a>
			<p class="text-helper text-ink-muted">Page {page} of {pageCount}</p>
			<a
				href={pageHref(page + 1)}
				aria-disabled={page >= pageCount}
				class="rounded-[7px] border border-line-control px-3 py-1.5 text-ui text-ink-secondary
					outline-none hover:bg-surface-raised/60 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-focus-ring
					focus-visible:outline-solid aria-disabled:pointer-events-none aria-disabled:opacity-40"
			>
				Next
			</a>
		</nav>
	{/if}

	{#if !readOnly}
		<!--
			The phone's primary action. `PrimaryAction` is `sticky`, not `fixed` — so at the bottom
			of the scroll it comes to rest AFTER the last card rather than on top of it, with no
			clearance padding to keep in sync. T22 makes that an acceptance criterion, and
			`shell.mobile.spec.ts` has asserted it since T08.
		-->
		<PrimaryAction class="lg:hidden" onclick={oncreate} disabled={creating}>
			{creating ? 'Starting…' : 'New invoice'}
		</PrimaryAction>
	{/if}
</div>
